spring:
  kafka:
    bootstrap-servers:
    - ${kafka.hostname:localhost}:9092
kafka:
  bootstrapAddress: ${kafka.hostname:localhost}:9092
  group:
    name:
      preanalysis: PreAnalysis
      workspace-update: WorkspaceUpdate
      process-execution: ProcessExecution
      ert-update: ErtUpdate
      dataingest: DATA_INGEST
      ert-update-ingest: ERT_UPDATE_FROM_INGESTION
      process-execution-scheduler: ProcessUpdateScheduler
      send-email: SendEmail
      audit: Auditing
      rdbms-ingest: RDBMS_INGEST
      ert-rdbms-scheduler-call: ErtRdbmsSchedulerCall
      ert-retry: ErtRetry
      deletion-workspace : deletionWorkspace
      database-deletion: DatabaseDeletion
      dclendToend-deletion: DclEndToEndDeletion
      workspace-adhoc-deletion: WorkspaceAdhocDeletion
      ert-session : ErtSession
     
      
  topic:
    name:
      preanalysis: PREANALYSIS
      workspace-update: WORKSPACE_UPDATE
      process-execution: PROCESS_UPDATE
      ert-update: ERT_UPDATE
      process-execution-scheduler: PROCESS_UPDATE_SCHEDULER
      send-email: SEND_EMAIL
      dataingest: DATA_INGEST
      ert-update-ingest: ERT_UPDATE_FROM_INGESTION
      audit: AUDITING
      rdbms-ingest: RDBMS_INGEST
      ert-rdbms-scheduler-call: ERT_RDBMS_SCHEDULER_CALL
      ert-retry: ERT_RETRY
      deletion-workspace: DELETION_WORKSPACE
      database-deletion: DATABASE_DELETION
      dclendToend-deletion: DCL_ENDTOEND_DELETION
      workspace-adhoc-deletion: WORKSPACE_ADHOC_DELETION
      ert-session : ERT_SESSION
   
