spring:
  kafka:
    bootstrap-servers:
    - localhost:9092
kafka:
  bootstrapAddress: localhost:9092
  group:
    name:
      preanalysis: PreAnalysis
  topic:
    name:
      preanalysis: PREANALYSIS